name: Feature request
description: Request a feature.
title: "[Feature]: "
labels: ["feature-request"]
projects: ["semAssessment"]
assignees:
  - group23
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Enter your mail address
    validations:
      required: false
  - type: textarea
    id: new-feature
    attributes:
      label: Request a feature
      description: What new feature do you wish to be integrated?
      placeholder: Explain the feature in detail!
      value: "Request a new feature!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
